feat: Support empty appid as interapp configure
linuxdeepin/dde-app-services pull request #32
Opened 2023-02-06 03:51 UTC by 18202781743

fallback to generic configuration if application is not changed,
and if generic configuration is changed, it will emit all related application's valueChanged.

Log: none
Influence: none
Change-Id: I90ad3bf631f69eb93445212a5cb6fab1c4ad1ec7

2023-02-06 05:57 UTC, asterwyx reviewed
+1

2023-02-16 09:41 UTC, 18202781743 commented
/review @FeiWang1119

2023-02-17 01:51 UTC, FeiWang1119 approved these changes

2023-02-21 11:41 UTC, asterwyx requested changes

2023-02-21 11:41 UTC, asterwyx commented on debian/control
> + libdtkcore-dev(>5.6.5),
这里是否是必要的。

2023-02-22 03:51 UTC, 18202781743 commented on dconfig-center/dde-dconfig-daemon/dconfig_global.h
> +    return connKey.startsWith("/" + VirtualInterAppId);
会出现，对于这种问题，下次提交整体上做个判断，

2023-02-22 03:54 UTC, 18202781743 commented on dconfig-center/dde-dconfig/main.cpp
> +    QCommandLineOption appidOption("a", QCoreApplication::translate("main", "appid for a specific application.\n"
在这里是一个选项，可以用小写

2023-02-22 06:28 UTC, asterwyx approved these changes

2023-02-22 06:28 UTC, merged