fix: Cleaning resource When exiting manual
linuxdeepin/dde-app-services pull request #40
Opened 2023-03-14 07:49 UTC by 18202781743

Modify log format.
  Call `exit` to clean resource when exiting.

2023-03-14 08:34 UTC, asterwyx requested changes

2023-03-14 08:34 UTC, asterwyx commented on dconfig-center/dde-dconfig-daemon/dconfigresource.cpp
> +    qDebug(cfLog()) << QString("Save resource's cache for [%1], and cache count:%2").arg(m_key).arg(m_caches.count());
这样会不会导致最后的打印外面有一对引号，建议直接使用<<拼接，而不是使用QString.

2023-03-14 08:34 UTC, asterwyx commented on dconfig-center/dde-dconfig-daemon/main.cpp
>          return 1;
Successfully start dconfig daemon.
Fail to start dconfig daemon.

2023-03-14 08:34 UTC, asterwyx commented on dconfig-center/dde-dconfig-daemon/main.cpp
>          return 1;
Starting dconfig daemon succeeded.
Starting dconfig daemon failed.

2023-03-14 10:08 UTC, 18202781743 commented on dconfig-center/dde-dconfig-daemon/dconfigresource.cpp
> +    qDebug(cfLog()) << QString("Save resource's cache for [%1], and cache count:%2").arg(m_key).arg(m_caches.count());
对于引号的，改成qCDebug，或者单独加了qPrintable来去掉引号

2023-03-15 01:50 UTC, kegechen approved these changes

2023-03-15 01:55 UTC, asterwyx approved these changes

2023-03-15 02:29 UTC, merged